### ISSUE TITLE
Change default package.use.force behavior for "system-bootstrap"

### ISSUE THREAD

**Issue by fraxgut** [clang-musl-overlay/clang-musl-overlay#32]
I wanted to address an issue I encountered while installing dev-lang/rust for the first time in the "clang-musl-overlay" repository. Currently, the "system-bootstrap" package.use.force flag is set as a default, resulting in a circular dependency when installing dev-lang/rust.

In my opinion, it would be beneficial to unset the "system-bootstrap" as a package.use.force by default and instead consider setting it as a default package.use option. This change would help avoid the circular dependency issue when installing dev-lang/rust for newcomers.

Additionally, I would like to inquire if it's possible to provide a rust-bin alternative in the "clang-musl-overlay" repository. This would offer users the option to install a pre-compiled binary package, saving time and resources during the installation process.

**Comment by rnpnr** [comment]
There is another problem with `system-bootstrap` being forced on rust: if you start from a non-clang profile and then try to migrate you will never be able to build a rust that doesn't rely on `libgcc_s` being present since the unwind hack in the ebuild depends on `system-bootstrap` being unset.

**Comment by capezotte** [comment]
No longer the default as of https://github.com/clang-musl-overlay/clang-musl-overlay/commit/8752f0ada2e7b94497fe25ce09c3117e5e9c07f6.
