### ISSUE TITLE
what is purpose of virtual/rust in this repo?

### ISSUE THREAD

**Issue by dm9pZCAq** [clang-musl-overlay/clang-musl-overlay#38]
as i see it is just a copy from `::gento`, and if someone want to use `dev-lang/rust::clang-musl` they can just mask `dev-lang/rust::gentoo`

**Comment by capezotte** [comment]
Back in the Rust 1.6[89] days we wanted to allow people to build Rust against LLVM 16, which was not officially supported by Gentoo and was encoded in virtual/rust's SLOT variable.
